### ISSUE TITLE
UI pattern master/detail

### ISSUE THREAD

**Issue by fazouane-marouane** [s0/eradicate-exclusive-tech-terminology#12]
I don't know if this is the right place for this, but there's the UI pattern master/detail. Think mail readers for example, or github issues list.

I don't have suggestions except perhaps list/detail ?

Example: https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/DesigningwithStoryboards.html

**Comment by s0** [comment]
Potentially index, directory or summary instead of master?

**Comment by fazouane-marouane** [comment]
I love "index" ! It sums it up very well

**Comment by s0** [comment]
Sweet! Feel free to open a PR to add another section for `master`/`detail` in UI =)
