### ISSUE TITLE
Male/female (e.g. in USB)

### ISSUE THREAD

**Issue by simonsan** [s0/eradicate-exclusive-tech-terminology#13]
I have the same problem there as with the older primary/secondary wording. I think it's inherently wrong to focus on the sexes in this contexts as an "abstraction" of a connector. But I didn't come up with a different wording for now as the controlling structure is in both directions often. A computer can control a peripheral device, but can also be controlled by it. 🤔

**Comment by s0** [comment]
I've heard of plug / socket being used instead of male / female.

**Comment by simonsan** [comment]
> I've heard of plug / socket being used instead of male / female.

Makes sense (not English native here), should that be added to the [terms](https://github.com/s0/eradicate-exclusive-tech-terminology#terms)?

**Comment by s0** [comment]
> Makes sense (not English native here), should that be added to the [terms](https://github.com/s0/eradicate-exclusive-tech-terminology#terms)?

I think that's a good idea, please feel free to open a PR that adds that! =)
